### ISSUE TITLE
How to use resources?

### ISSUE THREAD

**Issue by ghost** [gradle-guides/building-java-applications#13]
Hello,

In the guide, there's no mention of using resources. May I ask if you could add some examples of these?

- How to add resources (images...) to the project.
- How to obtain the resources in run time.

Thank you,

**Comment by pledbrook** [comment]
The first is a reasonable request, although it would probably just be an XML or JSON file, since those would be easy for a user to create.

The second is really outside the scope of this guide, which is focused on building the project. I'm sure there are plenty of snippets online that explain how to access resources that are packaged with Java code in JARs and WARs. That's part of the issue: the way you access them will depend on what you're producing.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #267](https://github.com/gradle/guides/issues/267) via [**ZenHub**](https://www.zenhub.com/)
